changesDir: .changes
unreleasedDir: unreleased
headerPath: ""
versionHeaderPath: ""
versionFooterPath: ""
versionExt: md
envPrefix: CHANGIE
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
projects:
    - label: levee-driver
      key: levee-driver
      changelog: packages/levee-driver/CHANGELOG.md
      replacements:
          - path: packages/levee-driver/package.json
            find: '"version": ".*"'
            replace: '"version": "{{.VersionNoPrefix}}"'
    - label: levee-client
      key: levee-client
      changelog: packages/levee-client/CHANGELOG.md
      replacements:
          - path: packages/levee-client/package.json
            find: '"version": ".*"'
            replace: '"version": "{{.VersionNoPrefix}}"'
projectsVersionSeparator: /
kinds:
    - label: Added
      auto: minor
    - label: Fixed
      auto: patch
    - label: Performance
      auto: patch
    - label: Changed
      auto: patch
    - label: Reverted
      auto: patch
    - label: Dependencies
      auto: patch
    - label: Security
      auto: patch
newlines:
    afterChangelogHeader: 1
    afterChangelogVersion: 1
    afterKind: 1
    afterVersion: 1
    endOfVersion: 1
