[tools]
elixir = "1.18.4-otp-28"
erlang = "28.3"
gleam = "1.14.0"
hk = "latest"
just = "latest"
rebar = "3.26.0"
node = "22"
pnpm = "10.24.0"

[env]
GITHUB_REDIRECT_URI = "http://localhost:4000/auth/github/callback"
