defmodule LeveeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :levee

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_levee_key",
    signing_salt: "EeKbobN0",
    same_site: "Lax"
  ]

  # Fluid Framework WebSocket endpoint
  # Supports both JSON (vsn ~> 2.0.0, default) and msgpack (vsn ~> 3.0.0) serialization.
  # Clients select the format by passing vsn in the socket connection params.
  socket "/socket", LeveeWeb.UserSocket,
    websocket: [
      serializer: [
        {Phoenix.Socket.V2.JSONSerializer, "~> 2.0.0"},
        {LeveeWeb.MsgpackSerializer, "~> 3.0.0"}
      ]
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # CORS - allow requests from any origin
  plug CORSPlug, origin: "*"

  plug Plug.Static,
    at: "/",
    from: :levee,
    gzip: not code_reloading?,
    only: LeveeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LeveeWeb.Router
end
